from enum import Enum

# Types of commands
class Command(Enum):
    PUSH = "PUSH"
    POP = "POP"
    BOOL = "BOOL"
    ADD = "ADD"
    SUB = "SUB"
    MUL = "MUL"
    DIV = "DIV"
    REM = "REM"
    NEG = "NEG"
    SWAP = "SWAP"
    QUIT = "QUIT"
    ERROR = "ERROR"
    AND = "AND"
    OR = "OR"
    NOT = "NOT"
    EQUAL = "EQUAL"
    LESS = "LESS"
    BIND = "BIND"
    IF = "IF"
    LET = "LET"
    END = "END"
    FUN = "FUN"
    FUNEND = "FUNEND"
    CALL = "CALL"
    RETURN = "RETURN"
    INOUT = "INOUT"
